# Site Settings
title: My Resume
url: 'https://stephen776.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6

#Profile information
name: Stephen Jacobs
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Self-motivated software engineer with nearly a decade of experience implementing software solutions working for multiple startups and government. Comfortable working in demanding, fast-paced environments and contributing to strategies to bring products to market. Have helped to launch multiple products with startups in the Pittsburgh area, working with cross-functional teams to design and implement software solutions in support of core business models.'

#sidebar links
# email: stephenjacobs86@gmail.com
# phone: 724 344 7725
# website: blog.webjeda.com #do not add http://
stackoverflow: stackoverflow.com/users/story/428632?view=Timeline
linkedin: stephen-jacobs-7468b53a
github: stephen776
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
